name: Build Project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Nodejs 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install yarn
        run: npm install --global yarn
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn test:ci
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Nodejs 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install yarn
        run: npm install --global yarn
      - name: Install dependencies
        run: yarn
      - name: Build Project
        run: yarn build
